package com.uff.br.controllers;

import com.uff.br.entities.Aluno;
import com.uff.br.repository.AlunoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/aluno") // This means URL's start with /demo (after Application path)
public class AlunoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AlunoRepository alunoRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewAluno (@RequestBody Aluno aluno) {
        Aluno newAluno = alunoRepository.save(aluno);
        return new RequestStatus(HttpStatus.OK.value(), newAluno);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Aluno> getAllAluno() {
        // This returns a JSON or XML with the users
        return alunoRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeAluno (@PathVariable int id) {
        alunoRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}