package com.uff.br.controllers;

import com.uff.br.entities.AnoEscolaridade;
import com.uff.br.repository.AnoEscolaridadeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/AnoEscolaridade") // This means URL's start with /demo (after Application path)
public class AnoEscolaridadeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AnoEscolaridadeRepository anoescolaridadeRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewAnoEscolaridade (@RequestBody AnoEscolaridade anoesc) {
        AnoEscolaridade newAnoEscolaridade = anoescolaridadeRepository.save(anoesc);
        return new RequestStatus(HttpStatus.OK.value(), newAnoEscolaridade);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<AnoEscolaridade> getAllAnoEscolaridade() {
        // This returns a JSON or XML with the users
        return anoescolaridadeRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeAnoEscolaridade (@PathVariable int id) {
        anoescolaridadeRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}