package com.uff.br.controllers;


import com.uff.br.DTO.EnderecoDTO;
import com.uff.br.DTO.EnderecoRespostaDTO;
import com.uff.br.entities.Endereco;
import com.uff.br.services.EnderecoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;


@RestController // This means that this class is a Controller
@RequestMapping(path="/endereco") // This means URL's start with /demo (after Application path)
public class EnderecoController {
    private final EnderecoService enderecoService;

    @Autowired
    public EnderecoController(EnderecoService enderecoService) {
        this.enderecoService = enderecoService;
    }

    @PostMapping(path="") // Map ONLY POST Requests
    public ResponseEntity<EnderecoRespostaDTO> addNewEndereco (@RequestBody EnderecoDTO dto) {
        Endereco e = enderecoService.salvar(dto.convertToObject());
        return new ResponseEntity<>(EnderecoRespostaDTO.convertToDTO(e), HttpStatus.CREATED);
    }

    @GetMapping(path="")
    public Iterable<Endereco> findAll () {
        return enderecoService.getAll();
    }

    @DeleteMapping(path="/{id}")
    public RequestStatus removeEndereco (@PathVariable int id) {
        return enderecoService.removeEndereco(id);
    }
}





/*
package com.uff.br.controllers;


import com.uff.br.entities.Endereco;
import com.uff.br.repository.EnderecoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/endereco") // This means URL's start with /demo (after Application path)
public class EnderecoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EnderecoRepository enderecoRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewEndereco (@RequestBody Endereco endereco) {
        Endereco newEndereco = enderecoRepository.save(endereco);
        return new RequestStatus(HttpStatus.OK.value(), newEndereco);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Endereco> getAllEndereco() {
        // This returns a JSON or XML with the users
        return enderecoRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeEndereco (@PathVariable int id) {
        enderecoRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}*/
