package com.uff.br.controllers;

import com.uff.br.entities.FaleConosco;
import com.uff.br.repository.FaleConoscoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/FaleConosco") // This means URL's start with /demo (after Application path)
public class FaleConoscoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FaleConoscoRepository faleconoscoRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewFaleConosco (@RequestBody FaleConosco faleconosco) {
        FaleConosco newFaleConosco = faleconoscoRepository.save(faleconosco);
        return new RequestStatus(HttpStatus.OK.value(), newFaleConosco);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<FaleConosco> getAllFaleConosco() {
        // This returns a JSON or XML with the users
        return faleconoscoRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeFaleConosco (@PathVariable int id) {
        faleconoscoRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}