package com.uff.br.controllers;

import com.uff.br.entities.Funcionario;
import com.uff.br.repository.FuncionarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/funcionario") // This means URL's start with /demo (after Application path)
public class FuncionarioController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FuncionarioRepository funcionarioRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewFuncionario (@RequestBody Funcionario funcionario) {
        Funcionario newFuncionario = funcionarioRepository.save(funcionario);
        return new RequestStatus(HttpStatus.OK.value(), newFuncionario);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Funcionario> getAllFuncionario() {
        // This returns a JSON or XML with the users
        return funcionarioRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeFuncionario (@PathVariable int id) {
        funcionarioRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}