package com.uff.br.controllers;

import com.uff.br.entities.Noticia;
import com.uff.br.repository.NoticiaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/noticia") // This means URL's start with /demo (after Application path)
public class NoticiaController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NoticiaRepository noticiaRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNoticia (@RequestBody Noticia noticia) {
        Noticia newNoticia = noticiaRepository.save(noticia);
        return new RequestStatus(HttpStatus.OK.value(), newNoticia);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Noticia> getAllNoticia() {
        // This returns a JSON or XML with the users
        return noticiaRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeNoticia (@PathVariable int id) {
        noticiaRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}