package com.uff.br.controllers;

import com.uff.br.entities.Responsavel;
import com.uff.br.repository.ResponsavelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/responsavel") // This means URL's start with /demo (after Application path)
public class ResponsavelController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ResponsavelRepository responsavelRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewResponsavel (@RequestBody Responsavel responsavel) {
        Responsavel newResponsavel = responsavelRepository.save(responsavel);
        return new RequestStatus(HttpStatus.OK.value(), newResponsavel);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Responsavel> getAllResponsavel() {
        // This returns a JSON or XML with the users
        return responsavelRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeResponsavel (@PathVariable int id) {
        responsavelRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}