package com.uff.br.controllers;

import com.uff.br.entities.SolicitacaoHasResponsavel;
import com.uff.br.repository.SolicitacaoHasResponsavelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/SolicitacaoHasResponsavel") // This means URL's start with /demo (after Application path)
public class SolicitacaoHasResponsavelController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SolicitacaoHasResponsavelRepository solicitacaoHasResponsavelRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewSolicitacaoHasResponsavel (@RequestBody SolicitacaoHasResponsavel soliresp) {
        SolicitacaoHasResponsavel newSoliResp = solicitacaoHasResponsavelRepository.save(soliresp);
        return new RequestStatus(HttpStatus.OK.value(), newSoliResp);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<SolicitacaoHasResponsavel> getAllSolicitacaoHasResponsavel() {
        // This returns a JSON or XML with the users
        return solicitacaoHasResponsavelRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeSolicitacaoHasResponsavel (@PathVariable int id) {
        solicitacaoHasResponsavelRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}