package com.uff.br.controllers;

import com.uff.br.entities.Solicitacao;
import com.uff.br.repository.SolicitacaoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/solicitacao") // This means URL's start with /demo (after Application path)
public class SolicitacaoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SolicitacaoRepository solicitacaoRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewSolicitacao (@RequestBody Solicitacao solicitacao) {
        Solicitacao newSolicitacao = solicitacaoRepository.save(solicitacao);
        return new RequestStatus(HttpStatus.OK.value(), newSolicitacao);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Solicitacao> getAllSolicitacao() {
        // This returns a JSON or XML with the users
        return solicitacaoRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeSolicitacao (@PathVariable int id) {
        solicitacaoRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}