package com.uff.br.controllers;

import com.uff.br.entities.TipoFuncionario;
import com.uff.br.repository.TipoFuncionarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/TipoFuncionario") // This means URL's start with /demo (after Application path)
public class TipoFuncionarioController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TipoFuncionarioRepository tipoFuncionarioRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewTipoFuncionario (@RequestBody TipoFuncionario tipoFuncionario) {
        TipoFuncionario newtipoFuncionario = tipoFuncionarioRepository.save(tipoFuncionario);
        return new RequestStatus(HttpStatus.OK.value(), newtipoFuncionario);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<TipoFuncionario> getAllTipoFuncionario() {
        // This returns a JSON or XML with the users
        return tipoFuncionarioRepository.findAll();
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody RequestStatus removeTipoFuncionario (@PathVariable int id) {
        tipoFuncionarioRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}