package com.uff.br.controllers;

import com.uff.br.entities.UnidadeEscolarHasAnoEscolaridadePK;
import com.uff.br.repository.UnidadeEscolarHasAnoEscolaridadePkRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/UnidadeEscolarHasAnoEscolaridadePK") // This means URL's start with /demo (after Application path)
public class UnidadeEscolarHasAnoEscolaridadePKController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UnidadeEscolarHasAnoEscolaridadePkRepository unidadeEscolarHasAnoEscolaridadePkRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewUser (@RequestBody UnidadeEscolarHasAnoEscolaridadePK unidadeEscolarHasAnoEscolaridadePK) {
        UnidadeEscolarHasAnoEscolaridadePK newUnidadeEscolarHasAnoEscolaridadePK = unidadeEscolarHasAnoEscolaridadePkRepository.save(unidadeEscolarHasAnoEscolaridadePK);
        return new RequestStatus(HttpStatus.OK.value(), newUnidadeEscolarHasAnoEscolaridadePK);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<UnidadeEscolarHasAnoEscolaridadePK> getAllUnidadeEscolarHasAnoEscolaridadePK() {
        // This returns a JSON or XML with the users
        return unidadeEscolarHasAnoEscolaridadePkRepository.findAll();
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody RequestStatus removeUser (@PathVariable int id) {
        unidadeEscolarHasAnoEscolaridadePkRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}