package com.uff.br.controllers;

import com.uff.br.repository.UsuarioRepository;
import com.uff.br.entities.Usuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/UnidadeEscolarHasAnoEscolaridade") // This means URL's start with /demo (after Application path)
public class UnidadeEscolarHasAnoEscolaridade {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UnidadeEscolarHasAnoEscolaridadeRepository unidadexano;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewUnidadeEscolarHasAnoEscolaridade (@RequestBody UnidadeEscolarHasAnoEscolaridade unidxano) {
        UnidadeEscolarHasAnoEscolaridade newUnidadexAno = unidadexano.save(unidxano);
        return new RequestStatus(HttpStatus.OK.value(), newUnidadexAno);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<UnidadeEscolarHasAnoEscolaridade> getAllUnidadeEscolarHasAnoEscolaridade() {
        // This returns a JSON or XML with the users
        return unidadexano.findAll();
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody RequestStatus removeUnidadeEscolarHasAnoEscolaridade (@PathVariable int id) {
        unidadexano.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}