package com.uff.br.controllers;


import com.uff.br.entities.UnidadeEscolarHasAnoEscolaridade;
import com.uff.br.repository.UnidadeEscolarHasAnoEscolaridadeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/UnidadeEscolarHasAnoEscolaridade") // This means URL's start with /demo (after Application path)
public class UnidadeEscolarHasAnoEscolaridadeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UnidadeEscolarHasAnoEscolaridadeRepository unidadeEscolarAnoEscolaridadeRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewUnidadeEscolarHasAnoEscolaridade(@RequestBody UnidadeEscolarHasAnoEscolaridade unidadeEscAnoEsc) {
        UnidadeEscolarHasAnoEscolaridade newUnidadeEscolarAnoEscolaridade = unidadeEscolarAnoEscolaridadeRepository.save(unidadeEscAnoEsc);
        return new RequestStatus(HttpStatus.OK.value(), newUnidadeEscolarAnoEscolaridade);
    }

    @GetMapping(path="")
    public @ResponseBody
    Iterable<UnidadeEscolarHasAnoEscolaridade> getAllUnidadeEscolarHasAnoEscolaridade() {
        // This returns a JSON or XML with the users
        return unidadeEscolarAnoEscolaridadeRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public @ResponseBody RequestStatus removeUnidadeEscolar (@PathVariable int id) {
        unidadeEscolarAnoEscolaridadeRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}