package com.uff.br.controllers;

import com.uff.br.repository.UsuarioRepository;
import com.uff.br.entities.Usuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/UnidadeEscolarHasAnoEscolaridadePk") // This means URL's start with /demo (after Application path)
public class UnidadeEscolarHasAnoEscolaridadePk {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UnidadeEscolarHasAnoEscolaridadePkRepository unidadexanopk;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewUnidadeEscolarHasAnoEscolaridadePk (@RequestBody UnidadeEscolarHasAnoEscolaridadePk unidxanopk) {
        UnidadeEscolarHasAnoEscolaridadePk newUnidadexAnopk = unidadexanopk.save(unidxanopk);
        return new RequestStatus(HttpStatus.OK.value(), newUnidadexAnopk);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<UnidadeEscolarHasAnoEscolaridadePk> getAllUnidadeEscolarHasAnoEscolaridadePk() {
        // This returns a JSON or XML with the users
        return unidadexanopk.findAll();
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody RequestStatus removeUnidadeEscolarHasAnoEscolaridadePk (@PathVariable int id) {
        unidadexanopk.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}