package com.uff.br.controllers;

import com.uff.br.repository.UsuarioRepository;
import com.uff.br.entities.Usuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.uff.br.utils.RequestStatus;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UsuarioController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsuarioRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody RequestStatus addNewUser (@RequestBody Usuario usuario) {
        Usuario newUsuario = userRepository.save(usuario);
        return new RequestStatus(HttpStatus.OK.value(), newUsuario);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Usuario> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody RequestStatus removeUser (@PathVariable int id) {
        userRepository.deleteById(id);
        return new RequestStatus(HttpStatus.OK.value());
    }
}